### ISSUE TITLE
发布流程

### ISSUE THREAD

**Issue by haoxutong** [vision-app/CONTRIBUTING#5]
**cloud-ui组件库在NPM（https://www.npmjs.com） 官网上发包流程**
1. 在develop分支修改完之后要提交，然后checkout到master分支；
2. 在master分支merge develop分支的所有操作，修改package.json文件中的version字段为自己想要的版本号，然后commit；
3. 如果没有在NPM官网上注册过，请先在NPM官网上注册一个账号，然后执行npm adduser命令，按照提示，依次输入注册的用户名，密码和邮箱账户，当出现Logged in as hxtong on https://registry.npmjs.org/ 提示就表示成功；如果已经注册过的用户，并且发过包，请直接跳过这一步，进入第四步；
4. 执行npm publish 命令，会出现相应cloud-ui组件库版本号的提示信息；
5. 执行git push 操作，将修改内容提交；
6. 打tag，执行git tag v*.*.*，v后面是对应的版本号；
7. 执行git push origin v*.*.* 命令，将版本号提交到远程仓库；
8. 打开github网站，点击release，给对应的tag版本号写相应更新内容；
9. 发布完，还需将master分支的代码合并到develop分支上，保持代码分支代码一样

**Comment by z-ZYS-s** [comment]
已整理到：https://github.com/vusion/DOCUMENTATION/issues/4
